### ISSUE TITLE
equivalence/assoc only accepts a sequence of two-element lists

### ISSUE THREAD

**Issue by Postumius** [countvajhula/relation#6]
Line 252 of "equivalence.rkt"

The assoc function matches every pair with (list k v) so the match fails on some pairs. I think it should use (cons k v) instead, to be more in line with its contract as well as the base function.

Thank you

**Comment by countvajhula** [comment]
Fixed! Thank you for reporting it 👍

**Comment by Postumius** [comment]
Wow, thanks for the quick fix! And the great library
